Remove parent cells data structure from the code
sparta/sparta pull request #192
Opened 2020-11-04 15:59 UTC by sjplimp

## Purpose

Previously, a copy of all parent cells within the hierarchical grid were stored by every processor.  For large grids with many levels of adaptation this can consume a lot of memory.  With this change, parent cells are no longer stored, only child cells.

## Author(s)

Steve

## Backward Compatibility

This alters the syntax for the write_grid and read_grid commands, as well as the format for the file they write/read.  It replaces the nparent and nchild stat_style keywords with ngrid.  It enhances the options for the create_grid command.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

2020-11-04 16:03 UTC, sjplimp commented
Two features are not yet enabled by this PR:
(1) distributed explicit surfs - requires a new algorithm for finding grid/surf overlaps
(2) Kokkos - @stanmoore1 can you please look at this?

This should also be tested against all examples and regression tests we have to see if anything breaks.

2020-11-04 16:07 UTC, sjplimp commented
Also, I need to update the doc pages to reflect this new version,
including some minor changes to command syntax.

2020-11-06 17:40 UTC, aborner1 commented
@sjplimp How much memory does it take to store (child) cells in this new implementation? Still around 300 Bytes/cell?

2020-11-06 18:07 UTC, sjplimp commented
@aborner1 Essentially the same.  There is one extra int added to ChildCell, but that's in the noise.

2020-11-06 18:09 UTC, sjplimp commented
@aborner1 What is different is that each parent cell can no longer have an arbitrary grid of child cells within it.  Now, all the parent cells at level N have to define the same grid of child cells at level N+1.  Create_grid and adapt_grid did not expose this option previously, but in principle it was possible.

2020-11-06 18:12 UTC, sjplimp commented
@aborner1 Actually I was wrong about the memory.  There is no difference in ChildCell.  One int was removed and another added.

2020-11-06 22:07 UTC, stanmoore1 requested changes

2020-11-06 22:07 UTC, stanmoore1 commented on src/fix_ave_grid.cpp
> +	    }
Looks like wrong indentation, maybe left over from debugging?

2020-11-06 22:09 UTC, stanmoore1 commented
Kokkos now compiles, I'm running this through full Kokkos regression testing.

2020-11-09 15:11 UTC, stanmoore1 commented
@sjplimp I'm seeing a segfault with FFTs:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004dcbf5 in SPARTA_NS::ComputeFFTGrid::reallocate (
    this=this@entry=0x11642f0) at ../compute_fft_grid.cpp:614
614	      array_grid[map2[i]][icol] = gridwork[i];
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64 libibverbs-22.4-5.el7.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-22.4-5.el7.x86_64 sssd-client-1.16.5-10.el7_9.5.x86_64
(gdb) where
#0  0x00000000004dcbf5 in SPARTA_NS::ComputeFFTGrid::reallocate (
    this=this@entry=0x11642f0) at ../compute_fft_grid.cpp:614
#1  0x00000000004dd43a in SPARTA_NS::ComputeFFTGrid::ComputeFFTGrid (
    this=0x11642f0, sparta=<optimized out>, narg=13, arg=0xc6cd20)
    at ../compute_fft_grid.cpp:261
#2  0x0000000000569e77 in SPARTA_NS::Modify::add_compute (this=0xc687a0, 
    narg=13, arg=0xc6cd20) at ../compute_fft_grid.h:17
#3  0x000000000048f3ed in compute (this=0xc47cc0) at ../input.cpp:1245
#4  SPARTA_NS::Input::execute_command (this=this@entry=0xc47cc0)
    at ../input.cpp:673
#5  0x000000000048fea3 in SPARTA_NS::Input::file (this=0xc47cc0)
    at ../input.cpp:199
#6  0x0000000000406386 in main (argc=<optimized out>, argv=<optimized out>)
    at ../main.cpp:30
```

2020-11-09 15:43 UTC, stanmoore1 commented
I'm seeing a few failures with the `adapt` examples and Kokkos, looking into it now.

2020-11-09 21:53 UTC, stanmoore1 commented
The Kokkos issue is now fixed.

2020-11-13 21:05 UTC, stanmoore1 commented on src/grid.cpp
> +
Whitespace issue

2020-11-13 21:07 UTC, stanmoore1 commented on src/fix_ave_grid.cpp
> +	    }
@sjplimp

2020-11-17 16:54 UTC, stanmoore1 approved these changes
@sjplimp I think we should merge this when ready and fix whitespace issues in a separate PR.

2020-11-19 16:43 UTC, sjplimp commented
@stanmoore1 if this version passes all regression tests, it can be merged

2020-11-19 19:20 UTC, stanmoore1 approved these changes

2020-11-19 19:20 UTC, merged