new averaging option for fix temp/rescale
sparta/sparta pull request #334
Opened 2022-03-07 21:59 UTC by sjplimp

## Purpose

Add a new "ave" option to fix temp/rescale to allow the current thermal temperature used for velocity rescaling to be the average thermal temperature across all grid cells.  Rather than the thermal terperature for each individual cell, as is the current case. 

## Author(s)

Steve

## Backward Compatibility

N/A

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

2022-03-07 22:00 UTC, sjplimp commented
@stanmoore1 Please wait for Michael to test this.  Once it is ready, this option can be added to the Kokkos version as well.

2022-04-05 16:40 UTC, stanmoore1 requested changes

2022-04-05 16:40 UTC, stanmoore1 commented on src/fix_temp_rescale.cpp
> +    count = cinfo[icell].count;
Count should be `int` instead of `double`?

2022-04-05 16:40 UTC, stanmoore1 commented on src/fix_temp_rescale.cpp
> +      count = cinfo[icell].count;
Is this (`count = cinfo[icell].count`)needed?

2022-04-05 17:01 UTC, sjplimp commented
just pushed a modified version which I think addresses both Qs

2022-04-05 21:08 UTC, stanmoore1 approved these changes

2022-04-05 21:08 UTC, merged